// Canonical financial templates extracted from Base_Cálculo_Indicadores.xlsx
// These define the standard structure for BP (55 lines), DRE (25 lines), and 36 indicators

export const BP_TEMPLATE: Array<{ classificacao: string; conta: string; nivel: number }> = [
  // ATIVO
  { classificacao: "AT", conta: "Ativo Total", nivel: 0 },
  { classificacao: "AC", conta: "Ativo Circulante", nivel: 1 },
  { classificacao: "AF", conta: "Caixa e Equivalentes de Caixa", nivel: 2 },
  { classificacao: "AF", conta: "Aplicações Financeiras", nivel: 2 },
  { classificacao: "AO", conta: "Contas a Receber", nivel: 2 },
  { classificacao: "AO", conta: "Estoques", nivel: 2 },
  { classificacao: "AO", conta: "Ativos Biológicos", nivel: 2 },
  { classificacao: "AO", conta: "Tributos a Recuperar", nivel: 2 },
  { classificacao: "AO", conta: "Despesas Antecipadas", nivel: 2 },
  { classificacao: "AO", conta: "Outros Ativos Circulantes", nivel: 2 },
  { classificacao: "ANC", conta: "Ativo Realizável a Longo Prazo", nivel: 1 },
  { classificacao: "0", conta: "Aplicações Financeiras Avaliadas a Valor Justo - ALP", nivel: 2 },
  { classificacao: "0", conta: "Aplicações Financeiras Avaliadas ao Custo Amortizado - ALP", nivel: 2 },
  { classificacao: "0", conta: "Contas a Receber - ALP", nivel: 2 },
  { classificacao: "0", conta: "Estoques - ALP", nivel: 2 },
  { classificacao: "0", conta: "Ativos Biológicos - ALP", nivel: 2 },
  { classificacao: "0", conta: "Tributos Diferidos - ALP", nivel: 2 },
  { classificacao: "0", conta: "Despesas Antecipadas - ALP", nivel: 2 },
  { classificacao: "0", conta: "Créditos com Partes Relacionadas - ALP", nivel: 2 },
  { classificacao: "0", conta: "Outros Ativos Não Circulantes - ALP", nivel: 2 },
  { classificacao: "ANC", conta: "Investimentos - ALP", nivel: 1 },
  { classificacao: "ANC", conta: "Imobilizado - ALP", nivel: 1 },
  { classificacao: "ANC", conta: "Intangível - ALP", nivel: 1 },
  { classificacao: "ANC", conta: "Diferido - ALP", nivel: 1 },

  // PASSIVO
  { classificacao: "PT", conta: "Passivo Total", nivel: 0 },
  { classificacao: "PC", conta: "Passivo Circulante", nivel: 1 },
  { classificacao: "PO", conta: "Obrigações Sociais e Trabalhistas", nivel: 2 },
  { classificacao: "PO", conta: "Fornecedores", nivel: 2 },
  { classificacao: "PO", conta: "Obrigações Fiscais", nivel: 2 },
  { classificacao: "PF", conta: "Empréstimos e Financiamentos", nivel: 2 },
  { classificacao: "PF", conta: "Passivos com Partes Relacionadas", nivel: 2 },
  { classificacao: "PF", conta: "Dividendos e JCP a Pagar", nivel: 2 },
  { classificacao: "PF", conta: "Outros", nivel: 2 },
  { classificacao: "PF", conta: "Provisões", nivel: 2 },
  { classificacao: "PF", conta: "Passivos sobre Ativos Não-Correntes a Venda e Descontinuados", nivel: 2 },
  { classificacao: "PNC", conta: "Passivo Não Circulante", nivel: 1 },
  { classificacao: "0", conta: "Empréstimos e Financiamentos - PLP", nivel: 2 },
  { classificacao: "0", conta: "Passivos com Partes Relacionadas - PLP", nivel: 2 },
  { classificacao: "0", conta: "Outros - PLP", nivel: 2 },
  { classificacao: "0", conta: "Tributos Diferidos - PLP", nivel: 2 },
  { classificacao: "0", conta: "Adiantamento para Futuro Aumento Capital - PLP", nivel: 2 },
  { classificacao: "0", conta: "Provisões - PLP", nivel: 2 },
  { classificacao: "0", conta: "Passivos sobre Ativos Não-Correntes a Venda e Descontinuados - PLP", nivel: 2 },
  { classificacao: "0", conta: "Lucros e Receitas a Apropriar - PLP", nivel: 2 },
  { classificacao: "PNC", conta: "Participação dos Acionistas Não Controladores - PLP", nivel: 1 },

  // PATRIMÔNIO LÍQUIDO
  { classificacao: "PL", conta: "Patrimônio Líquido", nivel: 1 },
  { classificacao: "0", conta: "Capital Social Realizado", nivel: 2 },
  { classificacao: "0", conta: "Reservas de Capital", nivel: 2 },
  { classificacao: "0", conta: "Reservas de Reavaliação", nivel: 2 },
  { classificacao: "0", conta: "Reservas de Lucros", nivel: 2 },
  { classificacao: "0", conta: "Lucros/Prejuízos Acumulados", nivel: 2 },
  { classificacao: "0", conta: "Ajustes de Avaliação Patrimonial", nivel: 2 },
  { classificacao: "0", conta: "Ajustes Acumulados de Conversão", nivel: 2 },
  { classificacao: "0", conta: "Outros Resultados Abrangentes", nivel: 2 },
];

export const DRE_TEMPLATE: Array<{ conta: string; subtotal: boolean }> = [
  { conta: "Receita Bruta de Vendas e/ou Serviços", subtotal: false },
  { conta: "Deduções da Receita Bruta", subtotal: false },
  { conta: "Receita Líquida", subtotal: true },
  { conta: "Custo Operacional", subtotal: false },
  { conta: "Resultado Bruto", subtotal: true },
  { conta: "Despesas Gerais e Administrativas", subtotal: false },
  { conta: "Despesas Com Vendas", subtotal: false },
  { conta: "Perdas pela Não Recuperabilidade de Ativos", subtotal: false },
  { conta: "Outras Receitas Operacionais", subtotal: false },
  { conta: "Outras Despesas Operacionais", subtotal: false },
  { conta: "Resultado Operacional", subtotal: true },
  { conta: "Resultado da Equivalência Patrimonial", subtotal: false },
  { conta: "Resultado Financeiro", subtotal: false },
  { conta: "Receitas Financeiras", subtotal: false },
  { conta: "Despesas Financeiras", subtotal: false },
  { conta: "Resultado Não Operacional", subtotal: false },
  { conta: "Receitas", subtotal: false },
  { conta: "Despesas", subtotal: false },
  { conta: "Resultado Antes Tributação/Participações", subtotal: true },
  { conta: "Provisão para IR e Contribuição Social", subtotal: false },
  { conta: "IR Diferido", subtotal: false },
  { conta: "Participações/Contribuições Estatutárias", subtotal: false },
  { conta: "Reversão dos Juros sobre Capital Próprio", subtotal: false },
  { conta: "Part. de Acionistas Não Controladores", subtotal: false },
  { conta: "Lucro ou Prejuízo do Período", subtotal: true },
];

export const INDICADORES_TEMPLATE: Array<{
  tipo: string;
  nome: string;
  formula: string;
  tipoDado: "R$" | "%" | "Índice" | "Dias" | "Texto";
}> = [
  // Indicadores Operacionais
  { tipo: "Indicadores Operacionais", nome: "Receita Líquida", formula: "Receita Bruta (-) Impostos (-) Cancelamentos", tipoDado: "R$" },
  { tipo: "Indicadores Operacionais", nome: "Lucro Bruto", formula: "Receita Líquida (-) Custo Operacional", tipoDado: "R$" },
  { tipo: "Indicadores Operacionais", nome: "Lucro Operacional", formula: "Lucro Bruto (-) Despesas Gerais e Administrativas (-) Despesas Com Vendas (-) Perdas pela Não Recuperabilidade de Ativos (+) Outras Receitas Operacionais (+) Outras Despesas Operacionais", tipoDado: "R$" },
  { tipo: "Indicadores Operacionais", nome: "Lucro Líquido", formula: "Lucro Bruto (+) Resultado Financeiro (+) Resultado Não Operacional (-) Impostos sobre a Renda", tipoDado: "R$" },
  { tipo: "Indicadores Operacionais", nome: "NOPAT", formula: "Lucro Operacional × (1 - Impostos (34%))", tipoDado: "R$" },

  // Indicadores de Margens
  { tipo: "Indicadores de Margens", nome: "Margem Bruta", formula: "Lucro Bruto / Receita Líquida", tipoDado: "%" },
  { tipo: "Indicadores de Margens", nome: "Margem Operacional", formula: "Lucro Operacional / Receita Líquida", tipoDado: "%" },
  { tipo: "Indicadores de Margens", nome: "Margem Líquida", formula: "Lucro Líquido / Receita Líquida", tipoDado: "%" },

  // Indicadores de Liquidez
  { tipo: "Indicadores de Liquidez", nome: "Liquidez Imediata", formula: "Caixa e Equivalentes de Caixa / Passivo Circulante", tipoDado: "Índice" },
  { tipo: "Indicadores de Liquidez", nome: "Liquidez Seca", formula: "(Ativo Circulante - Estoques) / Passivo Circulante", tipoDado: "Índice" },
  { tipo: "Indicadores de Liquidez", nome: "Liquidez Corrente", formula: "Ativo Circulante / Passivo Circulante", tipoDado: "Índice" },
  { tipo: "Indicadores de Liquidez", nome: "Liquidez Geral", formula: "(Ativo Circulante + Ativo Realizável a Longo Prazo) / (Passivo Circulante + Passivo Não Circulante)", tipoDado: "Índice" },

  // Indicadores de Capital de Giro
  { tipo: "Indicadores de Capital de Giro", nome: "Capital de Giro (CDG)", formula: "Ativo Circulante - Passivo Circulante", tipoDado: "R$" },
  { tipo: "Indicadores de Capital de Giro", nome: "Necessidade de Capital de Giro (NCG)", formula: "Ativo Operacional - Passivo Operacional", tipoDado: "R$" },
  { tipo: "Indicadores de Capital de Giro", nome: "Saldo em Tesouraria (ST)", formula: "Capital de Giro (CDG) - Necessidade de Capital de Giro (NCG)", tipoDado: "R$" },
  { tipo: "Indicadores de Capital de Giro", nome: "Situação da empresa", formula: "Classificação baseada em CDG, NCG e ST", tipoDado: "Texto" },
  { tipo: "Indicadores de Capital de Giro", nome: "Prazo Médio Contas a Receber", formula: "(Contas a Receber × 365) / Receita Líquida", tipoDado: "Dias" },
  { tipo: "Indicadores de Capital de Giro", nome: "Prazo Médio Estoque", formula: "(Estoques × 365) / Custo Operacional", tipoDado: "Dias" },
  { tipo: "Indicadores de Capital de Giro", nome: "Prazo Médio Fornecedores", formula: "(Fornecedores × 365) / Custo Operacional", tipoDado: "Dias" },
  { tipo: "Indicadores de Capital de Giro", nome: "Ciclo Financeiro", formula: "Prazo Médio Contas a Receber + Prazo Médio Estoque - Prazo Médio Fornecedores", tipoDado: "Dias" },

  // Indicadores de Endividamento
  { tipo: "Indicadores de Endividamento", nome: "Caixa e Equivalentes", formula: "Caixa e Equivalentes de Caixa + Aplicações Financeiras + Aplicações Financeiras Avaliadas a Valor Justo - ALP + Aplicações Financeiras Avaliadas ao Custo Amortizado - ALP", tipoDado: "R$" },
  { tipo: "Indicadores de Endividamento", nome: "Capital de Terceiros", formula: "Empréstimos e Financiamentos + Passivos com Partes Relacionadas + Empréstimos e Financiamentos - PLP + Passivos com Partes Relacionadas - PLP", tipoDado: "R$" },
  { tipo: "Indicadores de Endividamento", nome: "Dívida Líquida", formula: "Capital de Terceiros - Caixa e Equivalentes", tipoDado: "R$" },
  { tipo: "Indicadores de Endividamento", nome: "Endividamento Geral", formula: "(Passivo Total - Patrimônio Líquido) / Passivo Total", tipoDado: "%" },
  { tipo: "Indicadores de Endividamento", nome: "Endividamento de Curto Prazo", formula: "Passivo Circulante / Passivo Total", tipoDado: "%" },
  { tipo: "Indicadores de Endividamento", nome: "Patrimônio Líquido", formula: "Patrimônio Líquido", tipoDado: "R$" },
  { tipo: "Indicadores de Endividamento", nome: "Capital Terceiros s/ PL", formula: "Capital de Terceiros / Patrimônio Líquido", tipoDado: "Índice" },
  { tipo: "Indicadores de Endividamento", nome: "Dívida Líquida/Lucro Operacional", formula: "Dívida Líquida / Lucro Operacional", tipoDado: "Índice" },
  { tipo: "Indicadores de Endividamento", nome: "Índice de Cobertura de Juros", formula: "Lucro Operacional / Despesas Financeiras", tipoDado: "Índice" },
  { tipo: "Indicadores de Endividamento", nome: "Despesa Financeira / Rec. Líquida", formula: "Despesas Financeiras / Receita Líquida", tipoDado: "%" },

  // Indicadores de Rentabilidade
  { tipo: "Indicadores de Rentabilidade", nome: "ROA (Retorno sobre Ativos)", formula: "Lucro ou Prejuízo do Período / Ativo Total", tipoDado: "%" },
  { tipo: "Indicadores de Rentabilidade", nome: "ROIC (Retorno sobre Capital Investido)", formula: "NOPAT / (Patrimônio Líquido + Capital de Terceiros)", tipoDado: "%" },

  // Indicadores de Rentabilidade - Modelo Dupont
  { tipo: "Indicadores de Rentabilidade - Modelo Dupont", nome: "ROE (Retorno sobre Patrimônio Líquido)", formula: "Lucro ou Prejuízo do Período / Patrimônio Líquido", tipoDado: "%" },
  { tipo: "Indicadores de Rentabilidade - Modelo Dupont", nome: "Margem Líquida", formula: "Lucro Líquido / Receita Líquida", tipoDado: "%" },
  { tipo: "Indicadores de Rentabilidade - Modelo Dupont", nome: "Giro do Ativo", formula: "Receita Líquida / Ativo Total", tipoDado: "Índice" },
  { tipo: "Indicadores de Rentabilidade - Modelo Dupont", nome: "Alavancagem", formula: "Passivo Total / Patrimônio Líquido", tipoDado: "Índice" },
];

// Account name aliases for normalization
// Maps common variations to the canonical name
export const ACCOUNT_ALIASES: Record<string, string> = {
  // Ativo
  "Disponibilidades": "Caixa e Equivalentes de Caixa",
  "Caixa e Bancos": "Caixa e Equivalentes de Caixa",
  "Caixa": "Caixa e Equivalentes de Caixa",
  "Disponível": "Caixa e Equivalentes de Caixa",
  "Bancos Conta Movimento": "Caixa e Equivalentes de Caixa",
  "Aplicações de Liquidez Imediata": "Aplicações Financeiras",
  "Investimentos de Curto Prazo": "Aplicações Financeiras",
  "Clientes": "Contas a Receber",
  "Duplicatas a Receber": "Contas a Receber",
  "Títulos a Receber": "Contas a Receber",
  "Mercadorias": "Estoques",
  "Produtos Acabados": "Estoques",
  "Matérias-Primas": "Estoques",
  "Estoque": "Estoques",
  "Impostos a Recuperar": "Tributos a Recuperar",
  "Créditos Tributários": "Tributos a Recuperar",
  "ICMS a Recuperar": "Tributos a Recuperar",
  "PIS a Recuperar": "Tributos a Recuperar",
  "COFINS a Recuperar": "Tributos a Recuperar",
  "Realizável a Longo Prazo": "Ativo Realizável a Longo Prazo",
  "Ativo Não Circulante": "Ativo Realizável a Longo Prazo",
  "Ativo Permanente": "Ativo Realizável a Longo Prazo",
  "Imobilizado": "Imobilizado - ALP",
  "Ativo Imobilizado": "Imobilizado - ALP",
  "Intangível": "Intangível - ALP",
  "Ativo Intangível": "Intangível - ALP",
  "Investimentos": "Investimentos - ALP",

  // Passivo
  "Obrigações Trabalhistas": "Obrigações Sociais e Trabalhistas",
  "Salários a Pagar": "Obrigações Sociais e Trabalhistas",
  "Encargos Sociais": "Obrigações Sociais e Trabalhistas",
  "Obrigações Tributárias": "Obrigações Fiscais",
  "Impostos a Pagar": "Obrigações Fiscais",
  "Tributos a Pagar": "Obrigações Fiscais",
  "ICMS a Recolher": "Obrigações Fiscais",
  "ISS a Recolher": "Obrigações Fiscais",
  "Financiamentos": "Empréstimos e Financiamentos",
  "Empréstimos": "Empréstimos e Financiamentos",
  "Empréstimos Bancários": "Empréstimos e Financiamentos",
  "Exigível a Longo Prazo": "Passivo Não Circulante",
  "Financiamentos de Longo Prazo": "Empréstimos e Financiamentos - PLP",
  "Empréstimos de Longo Prazo": "Empréstimos e Financiamentos - PLP",

  // PL
  "Capital Social": "Capital Social Realizado",
  "Capital Subscrito": "Capital Social Realizado",
  "Reserva de Lucros": "Reservas de Lucros",
  "Reserva Legal": "Reservas de Lucros",
  "Reserva de Capital": "Reservas de Capital",
  "Lucros Acumulados": "Lucros/Prejuízos Acumulados",
  "Prejuízos Acumulados": "Lucros/Prejuízos Acumulados",
  "Resultado Acumulado": "Lucros/Prejuízos Acumulados",

  // DRE
  "Receita Operacional Bruta": "Receita Bruta de Vendas e/ou Serviços",
  "Receita Bruta": "Receita Bruta de Vendas e/ou Serviços",
  "Faturamento Bruto": "Receita Bruta de Vendas e/ou Serviços",
  "(-) Deduções": "Deduções da Receita Bruta",
  "Deduções": "Deduções da Receita Bruta",
  "Impostos sobre Vendas": "Deduções da Receita Bruta",
  "Receita Operacional Líquida": "Receita Líquida",
  "Receita Líquida de Vendas": "Receita Líquida",
  "CMV": "Custo Operacional",
  "CPV": "Custo Operacional",
  "Custo das Mercadorias Vendidas": "Custo Operacional",
  "Custo dos Produtos Vendidos": "Custo Operacional",
  "Custo dos Serviços Prestados": "Custo Operacional",
  "Lucro Bruto": "Resultado Bruto",
  "Resultado Operacional Bruto": "Resultado Bruto",
  "Despesas Administrativas": "Despesas Gerais e Administrativas",
  "Despesas Gerais": "Despesas Gerais e Administrativas",
  "Despesas com Vendas": "Despesas Com Vendas",
  "Despesas Comerciais": "Despesas Com Vendas",
  "Lucro Operacional": "Resultado Operacional",
  "EBIT": "Resultado Operacional",
  "Resultado Operacional Líquido": "Resultado Operacional",
  "Equivalência Patrimonial": "Resultado da Equivalência Patrimonial",
  "Resultado Financeiro Líquido": "Resultado Financeiro",
  "LAIR": "Resultado Antes Tributação/Participações",
  "Lucro Antes do IR": "Resultado Antes Tributação/Participações",
  "Resultado Antes dos Tributos": "Resultado Antes Tributação/Participações",
  "IR e CSLL": "Provisão para IR e Contribuição Social",
  "Imposto de Renda": "Provisão para IR e Contribuição Social",
  "IRPJ e CSLL": "Provisão para IR e Contribuição Social",
  "Lucro Líquido": "Lucro ou Prejuízo do Período",
  "Prejuízo do Período": "Lucro ou Prejuízo do Período",
  "Resultado Líquido": "Lucro ou Prejuízo do Período",
  "Lucro/Prejuízo": "Lucro ou Prejuízo do Período",
  "Lucro do Exercício": "Lucro ou Prejuízo do Período",
  "Resultado do Exercício": "Lucro ou Prejuízo do Período",
};
